### ISSUE TITLE
zmq.error.ZMQError: Operation cannot be accomplished in current state

### ISSUE THREAD

**Issue by yding25** [chuangg/tdw-transport-challenge-starter-code#1]
Hi, 

I try the code (I do not use Docker) and it outputs an error.
How can I fix it?
------------------------------------------------------
connect: 1071
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    env = gym.make("transport_challenge-v0", train = 0, physics = True, port = 1071)
  File "/home/kitrob/anaconda3/lib/python3.8/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/kitrob/anaconda3/lib/python3.8/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/kitrob/anaconda3/lib/python3.8/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/home/kitrob/TMPTT/tdw-transport-challenge/tdw_transport_challenge/tdw_gym.py", line 42, in __init__
    self.controller = Controller(port=port, demo=demo, \
  File "/home/kitrob/TMPTT/tdw-transport-challenge/tdw_transport_challenge/controller.py", line 31, in __init__
    super().__init__(port=port, launch_build=False, \
  File "/home/kitrob/TMPTT/transport_challenge/transport_challenge/transport_controller.py", line 130, in __init__
    super().__init__(port=port, launch_build=launch_build, screen_width=screen_width, screen_height=screen_height,
  File "/home/kitrob/anaconda3/lib/python3.8/site-packages/magnebot/magnebot_controller.py", line 348, in __init__
    resp = self.communicate([{"$type": "set_img_pass_encoding",
  File "/home/kitrob/anaconda3/lib/python3.8/site-packages/magnebot/magnebot_controller.py", line 1240, in communicate
    resp = super().communicate(commands)
  File "/home/kitrob/anaconda3/lib/python3.8/site-packages/tdw/controller.py", line 79, in communicate
    self.socket.send_multipart(msg)
  File "/home/kitrob/anaconda3/lib/python3.8/site-packages/zmq/sugar/socket.py", line 447, in send_multipart
    return self.send(msg_parts[-1], flags, copy=copy, track=track)
  File "/home/kitrob/anaconda3/lib/python3.8/site-packages/zmq/sugar/socket.py", line 400, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 728, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 775, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 247, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/socket.pyx", line 242, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Operation cannot be accomplished in current state

**Comment by abhi1092** [comment]
If you have more than 1 TDW instance with same port running you will get this error. Try killing all running TDWs
