### ISSUE TITLE
NameError: name 'chain' is not defined in `magnebot_controller.py`

### ISSUE THREAD

**Issue by nnsriram97** [chuangg/tdw-transport-challenge-starter-code#5]
```
2021-07-19 22:22:03,465 - simple_example - DEBUG - {'type': 3, 'object': 0, 'arm': 'left'}
{'type': 3, 'object': 0, 'arm': 'left'}
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    obs, rewards, done, info = env.step(action)
.
.
.

    do_prismatic_first=target_position["y"] > Magnebot._TORSO_Y[Magnebot._DEFAULT_TORSO_Y])
  File "....../python3.7/site-packages/magnebot/magnebot_controller.py", line 1548, in _start_ik
    transformation_matrices = chain.forward_kinematics(ik, full_kinematics=True)
NameError: name 'chain' is not defined
```

Facing chain not defined in magnebot api when agent executes grasp action while running test.py

**Comment by abhi1092** [comment]
Hi, we haven't heard any updates on this issue so we are closing this for now. Please re-open if the issue still persists.
